SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/* ============================================================
   Cleanup (safe drop for re-run)
   ============================================================ */
IF OBJECT_ID(N'dbo.AI_DATASET', N'U') IS NOT NULL DROP TABLE dbo.AI_DATASET;
GO
IF OBJECT_ID(N'dbo.AI_KET_QUA', N'U') IS NOT NULL DROP TABLE dbo.AI_KET_QUA;
GO
IF OBJECT_ID(N'dbo.AI_LICH_SU_DU_DOAN', N'U') IS NOT NULL DROP TABLE dbo.AI_LICH_SU_DU_DOAN;
GO
IF OBJECT_ID(N'dbo.AI_NGUYEN_NHAN', N'U') IS NOT NULL DROP TABLE dbo.AI_NGUYEN_NHAN;
GO
IF OBJECT_ID(N'dbo.CT_DANH_GIA_DU_AN', N'U') IS NOT NULL DROP TABLE dbo.CT_DANH_GIA_DU_AN;
GO
IF OBJECT_ID(N'dbo.CT_DANH_GIA_NHAN_VIEN', N'U') IS NOT NULL DROP TABLE dbo.CT_DANH_GIA_NHAN_VIEN;
GO
IF OBJECT_ID(N'dbo.CT_KPI_CONG_VIEC', N'U') IS NOT NULL DROP TABLE dbo.CT_KPI_CONG_VIEC;
GO
IF OBJECT_ID(N'dbo.CT_CHI_PHI', N'U') IS NOT NULL DROP TABLE dbo.CT_CHI_PHI;
GO
IF OBJECT_ID(N'dbo.CT_CONG_VIEC', N'U') IS NOT NULL DROP TABLE dbo.CT_CONG_VIEC;
GO
IF OBJECT_ID(N'dbo.NHAT_KY_CHI_PHI', N'U') IS NOT NULL DROP TABLE dbo.NHAT_KY_CHI_PHI;
GO
IF OBJECT_ID(N'dbo.NHAT_KY_NHAN_SU', N'U') IS NOT NULL DROP TABLE dbo.NHAT_KY_NHAN_SU;
GO
IF OBJECT_ID(N'dbo.FILE_TIEN_DO_CONG_VIEC', N'U') IS NOT NULL DROP TABLE dbo.FILE_TIEN_DO_CONG_VIEC;
GO
IF OBJECT_ID(N'dbo.FILE_CONG_VIEC', N'U') IS NOT NULL DROP TABLE dbo.FILE_CONG_VIEC;
GO
IF OBJECT_ID(N'dbo.FILE_DU_AN', N'U') IS NOT NULL DROP TABLE dbo.FILE_DU_AN;
GO
IF OBJECT_ID(N'dbo.TIEN_DO_CONG_VIEC', N'U') IS NOT NULL DROP TABLE dbo.TIEN_DO_CONG_VIEC;
GO
IF OBJECT_ID(N'dbo.KPI_CONG_VIEC', N'U') IS NOT NULL DROP TABLE dbo.KPI_CONG_VIEC;
GO
IF OBJECT_ID(N'dbo.PHAN_CONG_CONG_VIEC', N'U') IS NOT NULL DROP TABLE dbo.PHAN_CONG_CONG_VIEC;
GO
IF OBJECT_ID(N'dbo.TIN_NHAN', N'U') IS NOT NULL DROP TABLE dbo.TIN_NHAN;
GO
IF OBJECT_ID(N'dbo.THANH_VIEN_PHONG_CHAT', N'U') IS NOT NULL DROP TABLE dbo.THANH_VIEN_PHONG_CHAT;
GO
IF OBJECT_ID(N'dbo.PHONG_CHAT', N'U') IS NOT NULL DROP TABLE dbo.PHONG_CHAT;
GO
IF OBJECT_ID(N'dbo.THANH_VIEN_DU_AN', N'U') IS NOT NULL DROP TABLE dbo.THANH_VIEN_DU_AN;
GO
IF OBJECT_ID(N'dbo.DANH_GIA_DU_AN', N'U') IS NOT NULL DROP TABLE dbo.DANH_GIA_DU_AN;
GO
IF OBJECT_ID(N'dbo.DANH_GIA_NHAN_VIEN', N'U') IS NOT NULL DROP TABLE dbo.DANH_GIA_NHAN_VIEN;
GO
IF OBJECT_ID(N'dbo.CHI_PHI', N'U') IS NOT NULL DROP TABLE dbo.CHI_PHI;
GO
IF OBJECT_ID(N'dbo.CONG_VIEC', N'U') IS NOT NULL DROP TABLE dbo.CONG_VIEC;
GO
IF OBJECT_ID(N'dbo.DANH_MUC_CONG_VIEC', N'U') IS NOT NULL DROP TABLE dbo.DANH_MUC_CONG_VIEC;
GO
IF OBJECT_ID(N'dbo.DU_AN', N'U') IS NOT NULL DROP TABLE dbo.DU_AN;
GO
IF OBJECT_ID(N'dbo.PHAN_QUYEN', N'U') IS NOT NULL DROP TABLE dbo.PHAN_QUYEN;
GO
IF OBJECT_ID(N'dbo.THANH_VIEN_NHOM', N'U') IS NOT NULL DROP TABLE dbo.THANH_VIEN_NHOM;
GO
IF OBJECT_ID(N'dbo.DANH_MUC_CHUC_NANG', N'U') IS NOT NULL DROP TABLE dbo.DANH_MUC_CHUC_NANG;
GO
IF OBJECT_ID(N'dbo.NHAN_VIEN', N'U') IS NOT NULL DROP TABLE dbo.NHAN_VIEN;
GO
IF OBJECT_ID(N'dbo.NHOM_NHAN_VIEN', N'U') IS NOT NULL DROP TABLE dbo.NHOM_NHAN_VIEN;
GO
IF OBJECT_ID(N'dbo.TRANG_THAI', N'U') IS NOT NULL DROP TABLE dbo.TRANG_THAI;
GO
IF OBJECT_ID(N'dbo.MUC_DO_UU_TIEN', N'U') IS NOT NULL DROP TABLE dbo.MUC_DO_UU_TIEN;
GO
IF OBJECT_ID(N'dbo.LOAI_DU_AN', N'U') IS NOT NULL DROP TABLE dbo.LOAI_DU_AN;
GO
IF OBJECT_ID(N'dbo.VAI_TRO', N'U') IS NOT NULL DROP TABLE dbo.VAI_TRO;
GO
IF OBJECT_ID(N'dbo.DANH_MUC_MAN_HINH', N'U') IS NOT NULL DROP TABLE dbo.DANH_MUC_MAN_HINH;
GO
IF OBJECT_ID(N'dbo.AI_MODEL', N'U') IS NOT NULL DROP TABLE dbo.AI_MODEL;
GO
IF OBJECT_ID(N'dbo.AspNetRoleClaims', N'U') IS NOT NULL DROP TABLE dbo.AspNetRoleClaims;
GO
IF OBJECT_ID(N'dbo.AspNetUserClaims', N'U') IS NOT NULL DROP TABLE dbo.AspNetUserClaims;
GO
IF OBJECT_ID(N'dbo.AspNetUserLogins', N'U') IS NOT NULL DROP TABLE dbo.AspNetUserLogins;
GO
IF OBJECT_ID(N'dbo.AspNetUserRoles', N'U') IS NOT NULL DROP TABLE dbo.AspNetUserRoles;
GO
IF OBJECT_ID(N'dbo.AspNetUserTokens', N'U') IS NOT NULL DROP TABLE dbo.AspNetUserTokens;
GO
IF OBJECT_ID(N'dbo.AspNetUsers', N'U') IS NOT NULL DROP TABLE dbo.AspNetUsers;
GO
IF OBJECT_ID(N'dbo.AspNetRoles', N'U') IS NOT NULL DROP TABLE dbo.AspNetRoles;
GO

/* ============================================================
   CREATE TABLE
   ============================================================ */
CREATE TABLE dbo.AI_MODEL
(
    MaModel       INT IDENTITY(1,1) NOT NULL,
    TenModel      NVARCHAR(255) NULL,
    DoChinhXac    FLOAT NULL,
    NgayTao       DATETIME NULL,
    MoTaModel     NVARCHAR(255) NULL
);
GO

CREATE TABLE dbo.AspNetRoles
(
    Id                  NVARCHAR(450) NOT NULL,
    Name                NVARCHAR(256) NULL,
    NormalizedName      NVARCHAR(256) NULL,
    ConcurrencyStamp    NVARCHAR(MAX) NULL
);
GO

CREATE TABLE dbo.AspNetUsers
(
    Id                    NVARCHAR(450) NOT NULL,
    HoTen                 NVARCHAR(100) NOT NULL,
    DiaChi                NVARCHAR(MAX) NOT NULL,
    SoDienThoai           NVARCHAR(20) NOT NULL,
    NgaySinh              DATETIME NOT NULL,
    Hinh                  VARBINARY(MAX) NULL,
    UserName              NVARCHAR(256) NULL,
    NormalizedUserName    NVARCHAR(256) NULL,
    Email                 NVARCHAR(256) NULL,
    NormalizedEmail       NVARCHAR(256) NULL,
    EmailConfirmed        BIT NOT NULL,
    PasswordHash          NVARCHAR(MAX) NULL,
    SecurityStamp         NVARCHAR(MAX) NULL,
    ConcurrencyStamp      NVARCHAR(MAX) NULL,
    PhoneNumber           NVARCHAR(MAX) NULL,
    PhoneNumberConfirmed  BIT NOT NULL,
    TwoFactorEnabled      BIT NOT NULL,
    LockoutEnd            DATETIME NULL,
    LockoutEnabled        BIT NOT NULL,
    AccessFailedCount     INT NOT NULL
);
GO

CREATE TABLE dbo.VAI_TRO
(
    MaVaiTro      INT IDENTITY(1,1) NOT NULL,
    TenVaiTro     NVARCHAR(255) NULL
);
GO

CREATE TABLE dbo.TRANG_THAI
(
    MaTrangThai    INT IDENTITY(1,1) NOT NULL,
    TenTrangThai   NVARCHAR(100) NULL,
    LoaiTrangThai  NVARCHAR(50) NULL,
    MoTaTrangThai  NVARCHAR(255) NULL
);
GO

CREATE TABLE dbo.LOAI_DU_AN
(
    MaLoaiDuAn      INT IDENTITY(1,1) NOT NULL,
    TenLoai         NVARCHAR(255) NULL,
    MoTaLoaiDuAn    NVARCHAR(255) NULL
);
GO

CREATE TABLE dbo.MUC_DO_UU_TIEN
(
    MaMucDo      INT IDENTITY(1,1) NOT NULL,
    TenMucDo     NVARCHAR(100) NULL,
    MoTaMucDo    NVARCHAR(255) NULL
);
GO

CREATE TABLE dbo.NHOM_NHAN_VIEN
(
    MaNhom      INT IDENTITY(1,1) NOT NULL,
    TenNhom     NVARCHAR(255) NULL,
    MoTaNhom    NVARCHAR(255) NULL
);
GO

CREATE TABLE dbo.DANH_MUC_MAN_HINH
(
    MaManHinh      INT IDENTITY(1,1) NOT NULL,
    TenManHinh     NVARCHAR(255) NULL,
    MoTaManHinh    NVARCHAR(255) NULL
);
GO

CREATE TABLE dbo.NHAN_VIEN
(
    MaNhanVien     INT IDENTITY(1,1) NOT NULL,
    MaVaiTro       INT NOT NULL,
    Id             NVARCHAR(450) NULL,
    HoTen          NVARCHAR(255) NULL,
    Email          VARCHAR(255) NULL,
    SoDienThoai    VARCHAR(20) NULL,
    CCCD           VARCHAR(15) NULL
);
GO

CREATE TABLE dbo.DU_AN
(
    MaDuAn               INT IDENTITY(1,1) NOT NULL,
    MaNhanVien           INT NOT NULL,
    MaTrangThai          INT NOT NULL,
    MaLoaiDuAn           INT NOT NULL,
    TenDuAn              NVARCHAR(255) NULL,
    MoTaDuAn             NVARCHAR(MAX) NULL,
    NgayBatDauDuAn       DATETIME NULL,
    NgayKetThucDuAn      DATETIME NULL,
    PhanTramHoanThanh    INT NULL
);
GO

CREATE TABLE dbo.DANH_MUC_CONG_VIEC
(
    MaDanhMucCV      INT IDENTITY(1,1) NOT NULL,
    MaDuAn           INT NOT NULL,
    TenDanhMucCV     NVARCHAR(255) NULL,
    MoTaDanhMucCV    NVARCHAR(255) NULL,
    NgayTaoDMCV      DATETIME NULL
);
GO

CREATE TABLE dbo.CONG_VIEC
(
    MaCongViec             INT IDENTITY(1,1) NOT NULL,
    MaDanhMucCV            INT NOT NULL,
    MaTrangThai            INT NOT NULL,
    MaMucDo                INT NOT NULL,
    TenCongViec            NVARCHAR(255) NULL,
    MoTaCongViec           NVARCHAR(MAX) NULL,
    NgayBatDauCongViec     DATETIME NULL,
    NgayKetThucCVDuKien    DATETIME NULL,
    NgayKetThucCVThucTe    DATETIME NULL,
    NgayTaoCongViec        DATETIME NULL
);
GO

CREATE TABLE dbo.KPI_CONG_VIEC
(
    MaKpi          INT IDENTITY(1,1) NOT NULL,
    MaCongViec     INT NOT NULL,
    TenKpi         NVARCHAR(255) NULL,
    MoTaKpi        NVARCHAR(255) NULL,
    DiemTongKpi    INT NULL,
    LoaiKpi        NVARCHAR(255) NULL
);
GO

CREATE TABLE dbo.TIEN_DO_CONG_VIEC
(
    MaTienDo           INT IDENTITY(1,1) NOT NULL,
    MaCongViec         INT NOT NULL,
    MaNhanVien         INT NOT NULL,
    PhanTram           INT NULL,
    GhiChuTienDo       NVARCHAR(255) NULL,
    ThoiGianCapNhat    DATETIME NULL CONSTRAINT DF_TIEN_DO_CONG_VIEC_ThoiGianCapNhat DEFAULT (GETDATE()),
    TrangThaiTienDo    NVARCHAR(50) NULL
);
GO

CREATE TABLE dbo.FILE_TIEN_DO_CONG_VIEC
(
    MaFileTDCV       INT IDENTITY(1,1) NOT NULL,
    MaTienDo         INT NOT NULL,
    TenFileTDCV      NVARCHAR(255) NULL,
    DuongDanFileTDCV NVARCHAR(500) NULL
);
GO

CREATE TABLE dbo.FILE_CONG_VIEC
(
    MaFileCV         INT IDENTITY(1,1) NOT NULL,
    MaCongViec       INT NOT NULL,
    TenFileCV        NVARCHAR(255) NULL,
    DuongDanFileCV   NVARCHAR(500) NULL
);
GO

CREATE TABLE dbo.FILE_DU_AN
(
    MaFileDA         INT IDENTITY(1,1) NOT NULL,
    MaDuAn           INT NOT NULL,
    TenFileDA        NVARCHAR(255) NULL,
    DuongDanFileDA   NVARCHAR(500) NULL
);
GO

CREATE TABLE dbo.CHI_PHI
(
    MaChiPhi         INT IDENTITY(1,1) NOT NULL,
    MaNhanVien       INT NOT NULL,
    MaDuAn           INT NOT NULL,
    NganSach         DECIMAL(18,2) NULL,
    MoTaChiPhi       NVARCHAR(255) NULL,
    NgayCapNhatCP    DATETIME NULL,
    TrangThaiChiPhi  NVARCHAR(50) NULL
);
GO

CREATE TABLE dbo.CT_CHI_PHI
(
    MaChiTietCP      INT IDENTITY(1,1) NOT NULL,
    MaCongViec       INT NOT NULL,
    MaChiPhi         INT NOT NULL,
    NoiDungChiPhi    NVARCHAR(MAX) NULL,
    SoTienDaChi      DECIMAL(18,2) NULL,
    NgayChi          DATETIME NULL,
    LoaiChiPhi       NVARCHAR(50) NULL
);
GO

CREATE TABLE dbo.CT_CONG_VIEC
(
    MaChiTietCV        INT IDENTITY(1,1) NOT NULL,
    MaCongViec         INT NOT NULL,
    NoiDungChiTietCV   NVARCHAR(MAX) NULL,
    NgayBatDau         DATETIME NULL,
    NgayKetThuc        DATETIME NULL
);
GO

CREATE TABLE dbo.NHAT_KY_CHI_PHI
(
    MaNhatKyCP      INT IDENTITY(1,1) NOT NULL,
    MaChiPhi        INT NOT NULL,
    MaCongViec      INT NOT NULL,
    MaNhanVien      INT NOT NULL,
    SoTienNKCP      DECIMAL(18,2) NULL,
    HanhDongNKCP    NVARCHAR(255) NULL,
    ThoiGianNKCP    DATETIME NULL CONSTRAINT DF_NHAT_KY_CHI_PHI_ThoiGianNKCP DEFAULT (GETDATE())
);
GO

CREATE TABLE dbo.NHAT_KY_NHAN_SU
(
    MaNhatKyNS      INT IDENTITY(1,1) NOT NULL,
    MaNhanVien      INT NOT NULL,
    MaCongViec      INT NOT NULL,
    MaDuAn          INT NOT NULL,
    HanhDongNKNS    NVARCHAR(255) NULL,
    ThoiGianNKNS    DATETIME NULL CONSTRAINT DF_NHAT_KY_NHAN_SU_ThoiGianNKNS DEFAULT (GETDATE())
);
GO

CREATE TABLE dbo.DANH_GIA_DU_AN
(
    MaDanhGiaDuAn      INT IDENTITY(1,1) NOT NULL,
    MaDuAn             INT NOT NULL,
    MaNhanVien         INT NOT NULL,
    DiemTongDanhGiaDA  INT NULL,
    NhanXetTongDuAn    NVARCHAR(255) NULL,
    NgayDanhGiaDA      DATETIME NULL
);
GO

CREATE TABLE dbo.CT_DANH_GIA_DU_AN
(
    MaChiTietDGDA    INT IDENTITY(1,1) NOT NULL,
    MaDanhGiaDuAn    INT NOT NULL,
    NhanXetDuAn      NVARCHAR(MAX) NULL,
    TieuChi          NVARCHAR(50) NULL,
    DiemDanhGiaDA    INT NULL
);
GO

CREATE TABLE dbo.DANH_GIA_NHAN_VIEN
(
    MaDanhGiaNhanVien    INT IDENTITY(1,1) NOT NULL,
    MaNhanVien           INT NOT NULL,
    MaDuAn               INT NOT NULL,
    NHA_MaNhanVien       INT NOT NULL,
    DiemTongDanhGiaNV    INT NULL,
    NgayDanhGiaNV        DATETIME NULL,
    XepLoai              NVARCHAR(50) NULL
);
GO

CREATE TABLE dbo.CT_DANH_GIA_NHAN_VIEN
(
    MaChiTietDGNV         INT IDENTITY(1,1) NOT NULL,
    MaKpi                 INT NOT NULL,
    MaDanhGiaNhanVien     INT NOT NULL,
    NoiDungDanhGiaNhanVien NVARCHAR(MAX) NULL,
    DiemDanhGiaNV         INT NULL
);
GO

CREATE TABLE dbo.CT_KPI_CONG_VIEC
(
    MaChiTietKPICV    INT IDENTITY(1,1) NOT NULL,
    MaKpi             INT NOT NULL,
    TinhTrangKpi      NVARCHAR(255) NULL,
    DiemKpi           INT NULL
);
GO

CREATE TABLE dbo.PHAN_CONG_CONG_VIEC
(
    MaNhanVien      INT NOT NULL,
    MaCongViec      INT NOT NULL,
    VaiTro          NVARCHAR(50) NULL,
    NgayGiaoViec    DATETIME NULL
);
GO

CREATE TABLE dbo.THANH_VIEN_DU_AN
(
    MaDuAn              INT NOT NULL,
    MaNhanVien          INT NOT NULL,
    VaiTroTrongDuAn     NVARCHAR(50) NULL,
    NgayThamGiaDuAn     DATETIME NULL
);
GO

CREATE TABLE dbo.PHONG_CHAT
(
    MaPhongChat    INT IDENTITY(1,1) NOT NULL,
    MaDuAn         INT NOT NULL,
    TenPhong       NVARCHAR(255) NULL
);
GO

CREATE TABLE dbo.THANH_VIEN_PHONG_CHAT
(
    MaPhongChat            INT NOT NULL,
    MaNhanVien            INT NOT NULL,
    VaiTroTrongPhongChat  NVARCHAR(50) NULL
);
GO

CREATE TABLE dbo.TIN_NHAN
(
    MaTinNhan       INT IDENTITY(1,1) NOT NULL,
    MaPhongChat     INT NOT NULL,
    MaNhanVien      INT NOT NULL,
    NoiDungTinNhan  NVARCHAR(MAX) NULL,
    ThoiGianGui     DATETIME NULL CONSTRAINT DF_TIN_NHAN_ThoiGianGui DEFAULT (GETDATE())
);
GO

CREATE TABLE dbo.DANH_MUC_CHUC_NANG
(
    MaChucNang      INT IDENTITY(1,1) NOT NULL,
    MaManHinh       INT NOT NULL,
    TenChucNang     NVARCHAR(255) NULL,
    MoTaChucNang    NVARCHAR(255) NULL
);
GO

CREATE TABLE dbo.PHAN_QUYEN
(
    MaNhom        INT NOT NULL,
    MaChucNang    INT NOT NULL,
    CoQuyen       BIT NULL
);
GO

CREATE TABLE dbo.THANH_VIEN_NHOM
(
    MaNhom            INT NOT NULL,
    MaNhanVien        INT NOT NULL,
    VaiTroTrongNhom   NVARCHAR(100) NULL
);
GO

CREATE TABLE dbo.AI_DATASET
(
    MaData               INT IDENTITY(1,1) NOT NULL,
    MaCongViec           INT NOT NULL,
    SoNgayTre            INT NULL,
    SoNhanVien           INT NULL,
    ChiPhiThucTe         DECIMAL(18,2) NULL,
    DoPhucTap            INT NULL,
    SoCongViecPhuThuoc   INT NULL,
    TongGioLam           FLOAT NULL,
    TrangThaiCuoi        NVARCHAR(50) NULL
);
GO

CREATE TABLE dbo.AI_KET_QUA
(
    MaAiKetQua           INT IDENTITY(1,1) NOT NULL,
    MaModel              INT NOT NULL,
    MaDuAn               INT NOT NULL,
    NguyenNhanDuDoan     NVARCHAR(255) NULL,
    DoTinCayKetQua       FLOAT NULL,
    ThoiGianDuDoanKetQua DATETIME NULL
);
GO

CREATE TABLE dbo.AI_LICH_SU_DU_DOAN
(
    MaAiLichSuDuDoan     INT IDENTITY(1,1) NOT NULL,
    MaModel              INT NOT NULL,
    MaCongViec           INT NOT NULL,
    KetQuaDuDoan         NVARCHAR(255) NULL,
    ThoiGianDuDoan       DATETIME NULL CONSTRAINT DF_AI_LICH_SU_DU_DOAN_ThoiGianDuDoan DEFAULT (GETDATE()),
    DoTinCay             FLOAT NULL
);
GO

CREATE TABLE dbo.AI_NGUYEN_NHAN
(
    MaNguyenNhan       INT IDENTITY(1,1) NOT NULL,
    MaCongViec         INT NOT NULL,
    LoaiNguyenNhan     NVARCHAR(100) NULL,
    MoTaNguyenNhan     NVARCHAR(MAX) NULL
);
GO

CREATE TABLE dbo.AspNetRoleClaims
(
    Id            INT IDENTITY(1,1) NOT NULL,
    Asp_Id        NVARCHAR(450) NOT NULL,
    ClaimType     NVARCHAR(MAX) NULL,
    ClaimValue    NVARCHAR(MAX) NULL
);
GO

CREATE TABLE dbo.AspNetUserClaims
(
    Id            INT IDENTITY(1,1) NOT NULL,
    Asp_Id        NVARCHAR(450) NOT NULL,
    ClaimType     NVARCHAR(MAX) NULL,
    ClaimValue    NVARCHAR(MAX) NULL
);
GO

CREATE TABLE dbo.AspNetUserLogins
(
    LoginProvider        NVARCHAR(450) NOT NULL,
    ProviderKey          NVARCHAR(450) NOT NULL,
    Id                   NVARCHAR(450) NOT NULL,
    ProviderDisplayName  NVARCHAR(MAX) NULL
);
GO

CREATE TABLE dbo.AspNetUserRoles
(
    Asp_Id     NVARCHAR(450) NOT NULL,
    Id         NVARCHAR(450) NOT NULL
);
GO

CREATE TABLE dbo.AspNetUserTokens
(
    Id               NVARCHAR(450) NOT NULL,
    LoginProvider    NVARCHAR(450) NOT NULL,
    Name             NVARCHAR(450) NOT NULL,
    Value            NVARCHAR(MAX) NULL
);
GO

/* ============================================================
   PRIMARY KEY
   ============================================================ */
ALTER TABLE dbo.AI_MODEL ADD CONSTRAINT PK_AI_MODEL PRIMARY KEY CLUSTERED (MaModel);
GO
ALTER TABLE dbo.AspNetRoles ADD CONSTRAINT PK_AspNetRoles PRIMARY KEY CLUSTERED (Id);
GO
ALTER TABLE dbo.AspNetUsers ADD CONSTRAINT PK_AspNetUsers PRIMARY KEY CLUSTERED (Id);
GO
ALTER TABLE dbo.VAI_TRO ADD CONSTRAINT PK_VAI_TRO PRIMARY KEY CLUSTERED (MaVaiTro);
GO
ALTER TABLE dbo.TRANG_THAI ADD CONSTRAINT PK_TRANG_THAI PRIMARY KEY CLUSTERED (MaTrangThai);
GO
ALTER TABLE dbo.LOAI_DU_AN ADD CONSTRAINT PK_LOAI_DU_AN PRIMARY KEY CLUSTERED (MaLoaiDuAn);
GO
ALTER TABLE dbo.MUC_DO_UU_TIEN ADD CONSTRAINT PK_MUC_DO_UU_TIEN PRIMARY KEY CLUSTERED (MaMucDo);
GO
ALTER TABLE dbo.NHOM_NHAN_VIEN ADD CONSTRAINT PK_NHOM_NHAN_VIEN PRIMARY KEY CLUSTERED (MaNhom);
GO
ALTER TABLE dbo.DANH_MUC_MAN_HINH ADD CONSTRAINT PK_DANH_MUC_MAN_HINH PRIMARY KEY CLUSTERED (MaManHinh);
GO
ALTER TABLE dbo.NHAN_VIEN ADD CONSTRAINT PK_NHAN_VIEN PRIMARY KEY CLUSTERED (MaNhanVien);
GO
ALTER TABLE dbo.DU_AN ADD CONSTRAINT PK_DU_AN PRIMARY KEY CLUSTERED (MaDuAn);
GO
ALTER TABLE dbo.DANH_MUC_CONG_VIEC ADD CONSTRAINT PK_DANH_MUC_CONG_VIEC PRIMARY KEY CLUSTERED (MaDanhMucCV);
GO
ALTER TABLE dbo.CONG_VIEC ADD CONSTRAINT PK_CONG_VIEC PRIMARY KEY CLUSTERED (MaCongViec);
GO
ALTER TABLE dbo.KPI_CONG_VIEC ADD CONSTRAINT PK_KPI_CONG_VIEC PRIMARY KEY CLUSTERED (MaKpi);
GO
ALTER TABLE dbo.TIEN_DO_CONG_VIEC ADD CONSTRAINT PK_TIEN_DO_CONG_VIEC PRIMARY KEY CLUSTERED (MaTienDo);
GO
ALTER TABLE dbo.FILE_TIEN_DO_CONG_VIEC ADD CONSTRAINT PK_FILE_TIEN_DO_CONG_VIEC PRIMARY KEY CLUSTERED (MaFileTDCV);
GO
ALTER TABLE dbo.FILE_CONG_VIEC ADD CONSTRAINT PK_FILE_CONG_VIEC PRIMARY KEY CLUSTERED (MaFileCV);
GO
ALTER TABLE dbo.FILE_DU_AN ADD CONSTRAINT PK_FILE_DU_AN PRIMARY KEY CLUSTERED (MaFileDA);
GO
ALTER TABLE dbo.CHI_PHI ADD CONSTRAINT PK_CHI_PHI PRIMARY KEY CLUSTERED (MaChiPhi);
GO
ALTER TABLE dbo.CT_CHI_PHI ADD CONSTRAINT PK_CT_CHI_PHI PRIMARY KEY CLUSTERED (MaChiTietCP);
GO
ALTER TABLE dbo.CT_CONG_VIEC ADD CONSTRAINT PK_CT_CONG_VIEC PRIMARY KEY CLUSTERED (MaChiTietCV);
GO
ALTER TABLE dbo.NHAT_KY_CHI_PHI ADD CONSTRAINT PK_NHAT_KY_CHI_PHI PRIMARY KEY CLUSTERED (MaNhatKyCP);
GO
ALTER TABLE dbo.NHAT_KY_NHAN_SU ADD CONSTRAINT PK_NHAT_KY_NHAN_SU PRIMARY KEY CLUSTERED (MaNhatKyNS);
GO
ALTER TABLE dbo.DANH_GIA_DU_AN ADD CONSTRAINT PK_DANH_GIA_DU_AN PRIMARY KEY CLUSTERED (MaDanhGiaDuAn);
GO
ALTER TABLE dbo.CT_DANH_GIA_DU_AN ADD CONSTRAINT PK_CT_DANH_GIA_DU_AN PRIMARY KEY CLUSTERED (MaChiTietDGDA);
GO
ALTER TABLE dbo.DANH_GIA_NHAN_VIEN ADD CONSTRAINT PK_DANH_GIA_NHAN_VIEN PRIMARY KEY CLUSTERED (MaDanhGiaNhanVien);
GO
ALTER TABLE dbo.CT_DANH_GIA_NHAN_VIEN ADD CONSTRAINT PK_CT_DANH_GIA_NHAN_VIEN PRIMARY KEY CLUSTERED (MaChiTietDGNV);
GO
ALTER TABLE dbo.CT_KPI_CONG_VIEC ADD CONSTRAINT PK_CT_KPI_CONG_VIEC PRIMARY KEY CLUSTERED (MaChiTietKPICV);
GO
ALTER TABLE dbo.PHAN_CONG_CONG_VIEC ADD CONSTRAINT PK_PHAN_CONG_CONG_VIEC PRIMARY KEY CLUSTERED (MaNhanVien, MaCongViec);
GO
ALTER TABLE dbo.THANH_VIEN_DU_AN ADD CONSTRAINT PK_THANH_VIEN_DU_AN PRIMARY KEY CLUSTERED (MaDuAn, MaNhanVien);
GO
ALTER TABLE dbo.PHONG_CHAT ADD CONSTRAINT PK_PHONG_CHAT PRIMARY KEY CLUSTERED (MaPhongChat);
GO
ALTER TABLE dbo.THANH_VIEN_PHONG_CHAT ADD CONSTRAINT PK_THANH_VIEN_PHONG_CHAT PRIMARY KEY CLUSTERED (MaPhongChat, MaNhanVien);
GO
ALTER TABLE dbo.TIN_NHAN ADD CONSTRAINT PK_TIN_NHAN PRIMARY KEY CLUSTERED (MaTinNhan);
GO
ALTER TABLE dbo.DANH_MUC_CHUC_NANG ADD CONSTRAINT PK_DANH_MUC_CHUC_NANG PRIMARY KEY CLUSTERED (MaChucNang);
GO
ALTER TABLE dbo.PHAN_QUYEN ADD CONSTRAINT PK_PHAN_QUYEN PRIMARY KEY CLUSTERED (MaNhom, MaChucNang);
GO
ALTER TABLE dbo.THANH_VIEN_NHOM ADD CONSTRAINT PK_THANH_VIEN_NHOM PRIMARY KEY CLUSTERED (MaNhom, MaNhanVien);
GO
ALTER TABLE dbo.AI_DATASET ADD CONSTRAINT PK_AI_DATASET PRIMARY KEY CLUSTERED (MaData);
GO
ALTER TABLE dbo.AI_KET_QUA ADD CONSTRAINT PK_AI_KET_QUA PRIMARY KEY CLUSTERED (MaAiKetQua);
GO
ALTER TABLE dbo.AI_LICH_SU_DU_DOAN ADD CONSTRAINT PK_AI_LICH_SU_DU_DOAN PRIMARY KEY CLUSTERED (MaAiLichSuDuDoan);
GO
ALTER TABLE dbo.AI_NGUYEN_NHAN ADD CONSTRAINT PK_AI_NGUYEN_NHAN PRIMARY KEY CLUSTERED (MaNguyenNhan);
GO
ALTER TABLE dbo.AspNetRoleClaims ADD CONSTRAINT PK_AspNetRoleClaims PRIMARY KEY CLUSTERED (Id);
GO
ALTER TABLE dbo.AspNetUserClaims ADD CONSTRAINT PK_AspNetUserClaims PRIMARY KEY CLUSTERED (Id);
GO
ALTER TABLE dbo.AspNetUserLogins ADD CONSTRAINT PK_AspNetUserLogins PRIMARY KEY CLUSTERED (LoginProvider, ProviderKey);
GO
ALTER TABLE dbo.AspNetUserRoles ADD CONSTRAINT PK_AspNetUserRoles PRIMARY KEY CLUSTERED (Asp_Id, Id);
GO
ALTER TABLE dbo.AspNetUserTokens ADD CONSTRAINT PK_AspNetUserTokens PRIMARY KEY CLUSTERED (Id, LoginProvider, Name);
GO

/* ============================================================
   FOREIGN KEY
   ============================================================ */
ALTER TABLE dbo.NHAN_VIEN
ADD CONSTRAINT FK_NHAN_VIEN_VAI_TRO
FOREIGN KEY (MaVaiTro) REFERENCES dbo.VAI_TRO(MaVaiTro);
GO

ALTER TABLE dbo.NHAN_VIEN
ADD CONSTRAINT FK_NHAN_VIEN_AspNetUsers
FOREIGN KEY (Id) REFERENCES dbo.AspNetUsers(Id);
GO

ALTER TABLE dbo.DU_AN
ADD CONSTRAINT FK_DU_AN_NHAN_VIEN
FOREIGN KEY (MaNhanVien) REFERENCES dbo.NHAN_VIEN(MaNhanVien);
GO

ALTER TABLE dbo.DU_AN
ADD CONSTRAINT FK_DU_AN_TRANG_THAI
FOREIGN KEY (MaTrangThai) REFERENCES dbo.TRANG_THAI(MaTrangThai);
GO

ALTER TABLE dbo.DU_AN
ADD CONSTRAINT FK_DU_AN_LOAI_DU_AN
FOREIGN KEY (MaLoaiDuAn) REFERENCES dbo.LOAI_DU_AN(MaLoaiDuAn);
GO

ALTER TABLE dbo.DANH_MUC_CONG_VIEC
ADD CONSTRAINT FK_DANH_MUC_CONG_VIEC_DU_AN
FOREIGN KEY (MaDuAn) REFERENCES dbo.DU_AN(MaDuAn);
GO

ALTER TABLE dbo.CONG_VIEC
ADD CONSTRAINT FK_CONG_VIEC_DANH_MUC_CONG_VIEC
FOREIGN KEY (MaDanhMucCV) REFERENCES dbo.DANH_MUC_CONG_VIEC(MaDanhMucCV);
GO

ALTER TABLE dbo.CONG_VIEC
ADD CONSTRAINT FK_CONG_VIEC_TRANG_THAI
FOREIGN KEY (MaTrangThai) REFERENCES dbo.TRANG_THAI(MaTrangThai);
GO

ALTER TABLE dbo.CONG_VIEC
ADD CONSTRAINT FK_CONG_VIEC_MUC_DO_UU_TIEN
FOREIGN KEY (MaMucDo) REFERENCES dbo.MUC_DO_UU_TIEN(MaMucDo);
GO

ALTER TABLE dbo.KPI_CONG_VIEC
ADD CONSTRAINT FK_KPI_CONG_VIEC_CONG_VIEC
FOREIGN KEY (MaCongViec) REFERENCES dbo.CONG_VIEC(MaCongViec);
GO

ALTER TABLE dbo.TIEN_DO_CONG_VIEC
ADD CONSTRAINT FK_TIEN_DO_CONG_VIEC_CONG_VIEC
FOREIGN KEY (MaCongViec) REFERENCES dbo.CONG_VIEC(MaCongViec);
GO

ALTER TABLE dbo.TIEN_DO_CONG_VIEC
ADD CONSTRAINT FK_TIEN_DO_CONG_VIEC_NHAN_VIEN
FOREIGN KEY (MaNhanVien) REFERENCES dbo.NHAN_VIEN(MaNhanVien);
GO

ALTER TABLE dbo.FILE_TIEN_DO_CONG_VIEC
ADD CONSTRAINT FK_FILE_TIEN_DO_CONG_VIEC_TIEN_DO_CONG_VIEC
FOREIGN KEY (MaTienDo) REFERENCES dbo.TIEN_DO_CONG_VIEC(MaTienDo);
GO

ALTER TABLE dbo.FILE_CONG_VIEC
ADD CONSTRAINT FK_FILE_CONG_VIEC_CONG_VIEC
FOREIGN KEY (MaCongViec) REFERENCES dbo.CONG_VIEC(MaCongViec);
GO

ALTER TABLE dbo.FILE_DU_AN
ADD CONSTRAINT FK_FILE_DU_AN_DU_AN
FOREIGN KEY (MaDuAn) REFERENCES dbo.DU_AN(MaDuAn);
GO

ALTER TABLE dbo.CHI_PHI
ADD CONSTRAINT FK_CHI_PHI_NHAN_VIEN
FOREIGN KEY (MaNhanVien) REFERENCES dbo.NHAN_VIEN(MaNhanVien);
GO

ALTER TABLE dbo.CHI_PHI
ADD CONSTRAINT FK_CHI_PHI_DU_AN
FOREIGN KEY (MaDuAn) REFERENCES dbo.DU_AN(MaDuAn);
GO

ALTER TABLE dbo.CT_CHI_PHI
ADD CONSTRAINT FK_CT_CHI_PHI_CONG_VIEC
FOREIGN KEY (MaCongViec) REFERENCES dbo.CONG_VIEC(MaCongViec);
GO

ALTER TABLE dbo.CT_CHI_PHI
ADD CONSTRAINT FK_CT_CHI_PHI_CHI_PHI
FOREIGN KEY (MaChiPhi) REFERENCES dbo.CHI_PHI(MaChiPhi);
GO

ALTER TABLE dbo.CT_CONG_VIEC
ADD CONSTRAINT FK_CT_CONG_VIEC_CONG_VIEC
FOREIGN KEY (MaCongViec) REFERENCES dbo.CONG_VIEC(MaCongViec);
GO

ALTER TABLE dbo.NHAT_KY_CHI_PHI
ADD CONSTRAINT FK_NHAT_KY_CHI_PHI_CHI_PHI
FOREIGN KEY (MaChiPhi) REFERENCES dbo.CHI_PHI(MaChiPhi);
GO

ALTER TABLE dbo.NHAT_KY_CHI_PHI
ADD CONSTRAINT FK_NHAT_KY_CHI_PHI_CONG_VIEC
FOREIGN KEY (MaCongViec) REFERENCES dbo.CONG_VIEC(MaCongViec);
GO

ALTER TABLE dbo.NHAT_KY_CHI_PHI
ADD CONSTRAINT FK_NHAT_KY_CHI_PHI_NHAN_VIEN
FOREIGN KEY (MaNhanVien) REFERENCES dbo.NHAN_VIEN(MaNhanVien);
GO

ALTER TABLE dbo.NHAT_KY_NHAN_SU
ADD CONSTRAINT FK_NHAT_KY_NHAN_SU_NHAN_VIEN
FOREIGN KEY (MaNhanVien) REFERENCES dbo.NHAN_VIEN(MaNhanVien);
GO

ALTER TABLE dbo.NHAT_KY_NHAN_SU
ADD CONSTRAINT FK_NHAT_KY_NHAN_SU_CONG_VIEC
FOREIGN KEY (MaCongViec) REFERENCES dbo.CONG_VIEC(MaCongViec);
GO

ALTER TABLE dbo.NHAT_KY_NHAN_SU
ADD CONSTRAINT FK_NHAT_KY_NHAN_SU_DU_AN
FOREIGN KEY (MaDuAn) REFERENCES dbo.DU_AN(MaDuAn);
GO

ALTER TABLE dbo.DANH_GIA_DU_AN
ADD CONSTRAINT FK_DANH_GIA_DU_AN_DU_AN
FOREIGN KEY (MaDuAn) REFERENCES dbo.DU_AN(MaDuAn);
GO

ALTER TABLE dbo.DANH_GIA_DU_AN
ADD CONSTRAINT FK_DANH_GIA_DU_AN_NHAN_VIEN
FOREIGN KEY (MaNhanVien) REFERENCES dbo.NHAN_VIEN(MaNhanVien);
GO

ALTER TABLE dbo.CT_DANH_GIA_DU_AN
ADD CONSTRAINT FK_CT_DANH_GIA_DU_AN_DANH_GIA_DU_AN
FOREIGN KEY (MaDanhGiaDuAn) REFERENCES dbo.DANH_GIA_DU_AN(MaDanhGiaDuAn);
GO

ALTER TABLE dbo.DANH_GIA_NHAN_VIEN
ADD CONSTRAINT FK_DANH_GIA_NHAN_VIEN_NHAN_VIEN_NguoiDuocDanhGia
FOREIGN KEY (MaNhanVien) REFERENCES dbo.NHAN_VIEN(MaNhanVien);
GO

ALTER TABLE dbo.DANH_GIA_NHAN_VIEN
ADD CONSTRAINT FK_DANH_GIA_NHAN_VIEN_NHAN_VIEN_NguoiDanhGia
FOREIGN KEY (NHA_MaNhanVien) REFERENCES dbo.NHAN_VIEN(MaNhanVien);
GO

ALTER TABLE dbo.DANH_GIA_NHAN_VIEN
ADD CONSTRAINT FK_DANH_GIA_NHAN_VIEN_DU_AN
FOREIGN KEY (MaDuAn) REFERENCES dbo.DU_AN(MaDuAn);
GO

ALTER TABLE dbo.CT_DANH_GIA_NHAN_VIEN
ADD CONSTRAINT FK_CT_DANH_GIA_NHAN_VIEN_KPI_CONG_VIEC
FOREIGN KEY (MaKpi) REFERENCES dbo.KPI_CONG_VIEC(MaKpi);
GO

ALTER TABLE dbo.CT_DANH_GIA_NHAN_VIEN
ADD CONSTRAINT FK_CT_DANH_GIA_NHAN_VIEN_DANH_GIA_NHAN_VIEN
FOREIGN KEY (MaDanhGiaNhanVien) REFERENCES dbo.DANH_GIA_NHAN_VIEN(MaDanhGiaNhanVien);
GO

ALTER TABLE dbo.CT_KPI_CONG_VIEC
ADD CONSTRAINT FK_CT_KPI_CONG_VIEC_KPI_CONG_VIEC
FOREIGN KEY (MaKpi) REFERENCES dbo.KPI_CONG_VIEC(MaKpi);
GO

ALTER TABLE dbo.PHAN_CONG_CONG_VIEC
ADD CONSTRAINT FK_PHAN_CONG_CONG_VIEC_NHAN_VIEN
FOREIGN KEY (MaNhanVien) REFERENCES dbo.NHAN_VIEN(MaNhanVien);
GO

ALTER TABLE dbo.PHAN_CONG_CONG_VIEC
ADD CONSTRAINT FK_PHAN_CONG_CONG_VIEC_CONG_VIEC
FOREIGN KEY (MaCongViec) REFERENCES dbo.CONG_VIEC(MaCongViec);
GO

ALTER TABLE dbo.THANH_VIEN_DU_AN
ADD CONSTRAINT FK_THANH_VIEN_DU_AN_DU_AN
FOREIGN KEY (MaDuAn) REFERENCES dbo.DU_AN(MaDuAn);
GO

ALTER TABLE dbo.THANH_VIEN_DU_AN
ADD CONSTRAINT FK_THANH_VIEN_DU_AN_NHAN_VIEN
FOREIGN KEY (MaNhanVien) REFERENCES dbo.NHAN_VIEN(MaNhanVien);
GO

ALTER TABLE dbo.PHONG_CHAT
ADD CONSTRAINT FK_PHONG_CHAT_DU_AN
FOREIGN KEY (MaDuAn) REFERENCES dbo.DU_AN(MaDuAn);
GO

ALTER TABLE dbo.THANH_VIEN_PHONG_CHAT
ADD CONSTRAINT FK_THANH_VIEN_PHONG_CHAT_PHONG_CHAT
FOREIGN KEY (MaPhongChat) REFERENCES dbo.PHONG_CHAT(MaPhongChat);
GO

ALTER TABLE dbo.THANH_VIEN_PHONG_CHAT
ADD CONSTRAINT FK_THANH_VIEN_PHONG_CHAT_NHAN_VIEN
FOREIGN KEY (MaNhanVien) REFERENCES dbo.NHAN_VIEN(MaNhanVien);
GO

ALTER TABLE dbo.TIN_NHAN
ADD CONSTRAINT FK_TIN_NHAN_PHONG_CHAT
FOREIGN KEY (MaPhongChat) REFERENCES dbo.PHONG_CHAT(MaPhongChat);
GO

ALTER TABLE dbo.TIN_NHAN
ADD CONSTRAINT FK_TIN_NHAN_NHAN_VIEN
FOREIGN KEY (MaNhanVien) REFERENCES dbo.NHAN_VIEN(MaNhanVien);
GO

ALTER TABLE dbo.DANH_MUC_CHUC_NANG
ADD CONSTRAINT FK_DANH_MUC_CHUC_NANG_DANH_MUC_MAN_HINH
FOREIGN KEY (MaManHinh) REFERENCES dbo.DANH_MUC_MAN_HINH(MaManHinh);
GO

ALTER TABLE dbo.PHAN_QUYEN
ADD CONSTRAINT FK_PHAN_QUYEN_NHOM_NHAN_VIEN
FOREIGN KEY (MaNhom) REFERENCES dbo.NHOM_NHAN_VIEN(MaNhom);
GO

ALTER TABLE dbo.PHAN_QUYEN
ADD CONSTRAINT FK_PHAN_QUYEN_DANH_MUC_CHUC_NANG
FOREIGN KEY (MaChucNang) REFERENCES dbo.DANH_MUC_CHUC_NANG(MaChucNang);
GO

ALTER TABLE dbo.THANH_VIEN_NHOM
ADD CONSTRAINT FK_THANH_VIEN_NHOM_NHOM_NHAN_VIEN
FOREIGN KEY (MaNhom) REFERENCES dbo.NHOM_NHAN_VIEN(MaNhom);
GO

ALTER TABLE dbo.THANH_VIEN_NHOM
ADD CONSTRAINT FK_THANH_VIEN_NHOM_NHAN_VIEN
FOREIGN KEY (MaNhanVien) REFERENCES dbo.NHAN_VIEN(MaNhanVien);
GO

ALTER TABLE dbo.AI_DATASET
ADD CONSTRAINT FK_AI_DATASET_CONG_VIEC
FOREIGN KEY (MaCongViec) REFERENCES dbo.CONG_VIEC(MaCongViec);
GO

ALTER TABLE dbo.AI_KET_QUA
ADD CONSTRAINT FK_AI_KET_QUA_AI_MODEL
FOREIGN KEY (MaModel) REFERENCES dbo.AI_MODEL(MaModel);
GO

ALTER TABLE dbo.AI_KET_QUA
ADD CONSTRAINT FK_AI_KET_QUA_DU_AN
FOREIGN KEY (MaDuAn) REFERENCES dbo.DU_AN(MaDuAn);
GO

ALTER TABLE dbo.AI_LICH_SU_DU_DOAN
ADD CONSTRAINT FK_AI_LICH_SU_DU_DOAN_AI_MODEL
FOREIGN KEY (MaModel) REFERENCES dbo.AI_MODEL(MaModel);
GO

ALTER TABLE dbo.AI_LICH_SU_DU_DOAN
ADD CONSTRAINT FK_AI_LICH_SU_DU_DOAN_CONG_VIEC
FOREIGN KEY (MaCongViec) REFERENCES dbo.CONG_VIEC(MaCongViec);
GO

ALTER TABLE dbo.AI_NGUYEN_NHAN
ADD CONSTRAINT FK_AI_NGUYEN_NHAN_CONG_VIEC
FOREIGN KEY (MaCongViec) REFERENCES dbo.CONG_VIEC(MaCongViec);
GO

ALTER TABLE dbo.AspNetRoleClaims
ADD CONSTRAINT FK_AspNetRoleClaims_AspNetRoles
FOREIGN KEY (Asp_Id) REFERENCES dbo.AspNetRoles(Id);
GO

ALTER TABLE dbo.AspNetUserClaims
ADD CONSTRAINT FK_AspNetUserClaims_AspNetUsers
FOREIGN KEY (Asp_Id) REFERENCES dbo.AspNetUsers(Id);
GO

ALTER TABLE dbo.AspNetUserLogins
ADD CONSTRAINT FK_AspNetUserLogins_AspNetUsers
FOREIGN KEY (Id) REFERENCES dbo.AspNetUsers(Id);
GO

ALTER TABLE dbo.AspNetUserRoles
ADD CONSTRAINT FK_AspNetUserRoles_AspNetUsers
FOREIGN KEY (Asp_Id) REFERENCES dbo.AspNetUsers(Id);
GO

ALTER TABLE dbo.AspNetUserRoles
ADD CONSTRAINT FK_AspNetUserRoles_AspNetRoles
FOREIGN KEY (Id) REFERENCES dbo.AspNetRoles(Id);
GO

ALTER TABLE dbo.AspNetUserTokens
ADD CONSTRAINT FK_AspNetUserTokens_AspNetUsers
FOREIGN KEY (Id) REFERENCES dbo.AspNetUsers(Id);
GO

/* ============================================================
   INDEX
   ============================================================ */
CREATE INDEX IX_NHAN_VIEN_MaVaiTro ON dbo.NHAN_VIEN (MaVaiTro);
GO
CREATE INDEX IX_NHAN_VIEN_Id ON dbo.NHAN_VIEN (Id);
GO
CREATE INDEX IX_DU_AN_MaNhanVien ON dbo.DU_AN (MaNhanVien);
GO
CREATE INDEX IX_DU_AN_MaTrangThai ON dbo.DU_AN (MaTrangThai);
GO
CREATE INDEX IX_DU_AN_MaLoaiDuAn ON dbo.DU_AN (MaLoaiDuAn);
GO
CREATE INDEX IX_DANH_MUC_CONG_VIEC_MaDuAn ON dbo.DANH_MUC_CONG_VIEC (MaDuAn);
GO
CREATE INDEX IX_CONG_VIEC_MaDanhMucCV ON dbo.CONG_VIEC (MaDanhMucCV);
GO
CREATE INDEX IX_CONG_VIEC_MaTrangThai ON dbo.CONG_VIEC (MaTrangThai);
GO
CREATE INDEX IX_CONG_VIEC_MaMucDo ON dbo.CONG_VIEC (MaMucDo);
GO
CREATE INDEX IX_KPI_CONG_VIEC_MaCongViec ON dbo.KPI_CONG_VIEC (MaCongViec);
GO
CREATE INDEX IX_TIEN_DO_CONG_VIEC_MaCongViec ON dbo.TIEN_DO_CONG_VIEC (MaCongViec);
GO
CREATE INDEX IX_TIEN_DO_CONG_VIEC_MaNhanVien ON dbo.TIEN_DO_CONG_VIEC (MaNhanVien);
GO
CREATE INDEX IX_FILE_TIEN_DO_CONG_VIEC_MaTienDo ON dbo.FILE_TIEN_DO_CONG_VIEC (MaTienDo);
GO
CREATE INDEX IX_FILE_CONG_VIEC_MaCongViec ON dbo.FILE_CONG_VIEC (MaCongViec);
GO
CREATE INDEX IX_FILE_DU_AN_MaDuAn ON dbo.FILE_DU_AN (MaDuAn);
GO
CREATE INDEX IX_CHI_PHI_MaNhanVien ON dbo.CHI_PHI (MaNhanVien);
GO
CREATE INDEX IX_CHI_PHI_MaDuAn ON dbo.CHI_PHI (MaDuAn);
GO
CREATE INDEX IX_CT_CHI_PHI_MaCongViec ON dbo.CT_CHI_PHI (MaCongViec);
GO
CREATE INDEX IX_CT_CHI_PHI_MaChiPhi ON dbo.CT_CHI_PHI (MaChiPhi);
GO
CREATE INDEX IX_CT_CONG_VIEC_MaCongViec ON dbo.CT_CONG_VIEC (MaCongViec);
GO
CREATE INDEX IX_NHAT_KY_CHI_PHI_MaChiPhi ON dbo.NHAT_KY_CHI_PHI (MaChiPhi);
GO
CREATE INDEX IX_NHAT_KY_CHI_PHI_MaCongViec ON dbo.NHAT_KY_CHI_PHI (MaCongViec);
GO
CREATE INDEX IX_NHAT_KY_CHI_PHI_MaNhanVien ON dbo.NHAT_KY_CHI_PHI (MaNhanVien);
GO
CREATE INDEX IX_NHAT_KY_NHAN_SU_MaNhanVien ON dbo.NHAT_KY_NHAN_SU (MaNhanVien);
GO
CREATE INDEX IX_NHAT_KY_NHAN_SU_MaCongViec ON dbo.NHAT_KY_NHAN_SU (MaCongViec);
GO
CREATE INDEX IX_NHAT_KY_NHAN_SU_MaDuAn ON dbo.NHAT_KY_NHAN_SU (MaDuAn);
GO
CREATE INDEX IX_DANH_GIA_DU_AN_MaDuAn ON dbo.DANH_GIA_DU_AN (MaDuAn);
GO
CREATE INDEX IX_DANH_GIA_DU_AN_MaNhanVien ON dbo.DANH_GIA_DU_AN (MaNhanVien);
GO
CREATE INDEX IX_CT_DANH_GIA_DU_AN_MaDanhGiaDuAn ON dbo.CT_DANH_GIA_DU_AN (MaDanhGiaDuAn);
GO
CREATE INDEX IX_DANH_GIA_NHAN_VIEN_MaNhanVien ON dbo.DANH_GIA_NHAN_VIEN (MaNhanVien);
GO
CREATE INDEX IX_DANH_GIA_NHAN_VIEN_NHA_MaNhanVien ON dbo.DANH_GIA_NHAN_VIEN (NHA_MaNhanVien);
GO
CREATE INDEX IX_DANH_GIA_NHAN_VIEN_MaDuAn ON dbo.DANH_GIA_NHAN_VIEN (MaDuAn);
GO
CREATE INDEX IX_CT_DANH_GIA_NHAN_VIEN_MaKpi ON dbo.CT_DANH_GIA_NHAN_VIEN (MaKpi);
GO
CREATE INDEX IX_CT_DANH_GIA_NHAN_VIEN_MaDanhGiaNhanVien ON dbo.CT_DANH_GIA_NHAN_VIEN (MaDanhGiaNhanVien);
GO
CREATE INDEX IX_CT_KPI_CONG_VIEC_MaKpi ON dbo.CT_KPI_CONG_VIEC (MaKpi);
GO
CREATE INDEX IX_PHAN_CONG_CONG_VIEC_MaCongViec ON dbo.PHAN_CONG_CONG_VIEC (MaCongViec);
GO
CREATE INDEX IX_THANH_VIEN_DU_AN_MaNhanVien ON dbo.THANH_VIEN_DU_AN (MaNhanVien);
GO
CREATE INDEX IX_PHONG_CHAT_MaDuAn ON dbo.PHONG_CHAT (MaDuAn);
GO
CREATE INDEX IX_THANH_VIEN_PHONG_CHAT_MaNhanVien ON dbo.THANH_VIEN_PHONG_CHAT (MaNhanVien);
GO
CREATE INDEX IX_TIN_NHAN_MaPhongChat ON dbo.TIN_NHAN (MaPhongChat);
GO
CREATE INDEX IX_TIN_NHAN_MaNhanVien ON dbo.TIN_NHAN (MaNhanVien);
GO
CREATE INDEX IX_DANH_MUC_CHUC_NANG_MaManHinh ON dbo.DANH_MUC_CHUC_NANG (MaManHinh);
GO
CREATE INDEX IX_PHAN_QUYEN_MaChucNang ON dbo.PHAN_QUYEN (MaChucNang);
GO
CREATE INDEX IX_THANH_VIEN_NHOM_MaNhanVien ON dbo.THANH_VIEN_NHOM (MaNhanVien);
GO
CREATE INDEX IX_AI_DATASET_MaCongViec ON dbo.AI_DATASET (MaCongViec);
GO
CREATE INDEX IX_AI_KET_QUA_MaModel ON dbo.AI_KET_QUA (MaModel);
GO
CREATE INDEX IX_AI_KET_QUA_MaDuAn ON dbo.AI_KET_QUA (MaDuAn);
GO
CREATE INDEX IX_AI_LICH_SU_DU_DOAN_MaModel ON dbo.AI_LICH_SU_DU_DOAN (MaModel);
GO
CREATE INDEX IX_AI_LICH_SU_DU_DOAN_MaCongViec ON dbo.AI_LICH_SU_DU_DOAN (MaCongViec);
GO
CREATE INDEX IX_AI_NGUYEN_NHAN_MaCongViec ON dbo.AI_NGUYEN_NHAN (MaCongViec);
GO
CREATE INDEX IX_AspNetRoleClaims_Asp_Id ON dbo.AspNetRoleClaims (Asp_Id);
GO
CREATE INDEX IX_AspNetUserClaims_Asp_Id ON dbo.AspNetUserClaims (Asp_Id);
GO
CREATE INDEX IX_AspNetUserLogins_Id ON dbo.AspNetUserLogins (Id);
GO
CREATE INDEX IX_AspNetUserRoles_Id ON dbo.AspNetUserRoles (Id);
GO
