// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyDuAn.Data;

#nullable disable

namespace QuanLyDuAn.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.AiDataset", b =>
                {
                    b.Property<int>("MaData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaData"));

                    b.Property<decimal?>("ChiPhiDuKien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ChiPhiThucTe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaCongViec")
                        .HasColumnType("int");

                    b.Property<int>("MaDuAn")
                        .HasColumnType("int");

                    b.Property<string>("NguyenNhanChinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SoLanDelay")
                        .HasColumnType("int");

                    b.Property<int?>("SoLanThayDoiNhanSu")
                        .HasColumnType("int");

                    b.Property<int?>("SoNgayDuKienCV")
                        .HasColumnType("int");

                    b.Property<int?>("SoNgayThucTeCV")
                        .HasColumnType("int");

                    b.Property<int?>("SoNgayTreTienDo")
                        .HasColumnType("int");

                    b.Property<int?>("SoNhanVienDuAn")
                        .HasColumnType("int");

                    b.Property<double?>("TongGioLam")
                        .HasColumnType("float");

                    b.Property<string>("TrangThaiCuoi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaData");

                    b.HasIndex("MaCongViec");

                    b.HasIndex("MaDuAn");

                    b.ToTable("AI_DATASET", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.AiKetQua", b =>
                {
                    b.Property<int>("MaAiKetQua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAiKetQua"));

                    b.Property<double?>("DoTinCayKetQua")
                        .HasColumnType("float");

                    b.Property<int>("MaDuAn")
                        .HasColumnType("int");

                    b.Property<int>("MaModel")
                        .HasColumnType("int");

                    b.Property<string>("NguyenNhanDuDoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianDuDoanKetQua")
                        .HasColumnType("datetime2");

                    b.HasKey("MaAiKetQua");

                    b.HasIndex("MaDuAn");

                    b.HasIndex("MaModel");

                    b.ToTable("AI_KET_QUA", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.AiLichSuDuDoan", b =>
                {
                    b.Property<int>("MaAiLichSuDuDoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAiLichSuDuDoan"));

                    b.Property<double?>("DoTinCay")
                        .HasColumnType("float");

                    b.Property<string>("KetQuaDuDoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaCongViec")
                        .HasColumnType("int");

                    b.Property<int>("MaModel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianDuDoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("MaAiLichSuDuDoan");

                    b.HasIndex("MaCongViec");

                    b.HasIndex("MaModel");

                    b.ToTable("AI_LICH_SU_DU_DOAN", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.AiModel", b =>
                {
                    b.Property<int>("MaModel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaModel"));

                    b.Property<double?>("DoChinhXac")
                        .HasColumnType("float");

                    b.Property<string>("MoTaModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenModel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaModel");

                    b.ToTable("AI_MODEL", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.AiNguyenNhan", b =>
                {
                    b.Property<int>("MaNguyenNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguyenNhan"));

                    b.Property<string>("LoaiNguyenNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaCongViec")
                        .HasColumnType("int");

                    b.Property<string>("MoTaNguyenNhan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNguyenNhan");

                    b.HasIndex("MaCongViec");

                    b.ToTable("AI_NGUYEN_NHAN", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.ChiPhi", b =>
                {
                    b.Property<int>("MaChiPhi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiPhi"));

                    b.Property<int>("MaDuAn")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("MoTaChiPhi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NganSach")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("NgayCapNhatCp")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhatCP");

                    b.Property<string>("TrangThaiChiPhi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChiPhi");

                    b.HasIndex("MaDuAn");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("CHI_PHI", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.CongViec", b =>
                {
                    b.Property<int>("MaCongViec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCongViec"));

                    b.Property<int>("MaDanhMucCv")
                        .HasColumnType("int")
                        .HasColumnName("MaDanhMucCV");

                    b.Property<int>("MaMucDo")
                        .HasColumnType("int");

                    b.Property<int>("MaTrangThai")
                        .HasColumnType("int");

                    b.Property<string>("MoTaCongViec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDauCongViec")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThucCvDuKien")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayKetThucCVDuKien");

                    b.Property<DateTime?>("NgayKetThucCvThucTe")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayKetThucCVThucTe");

                    b.Property<DateTime?>("NgayTaoCongViec")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenCongViec")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCongViec");

                    b.HasIndex("MaDanhMucCv");

                    b.HasIndex("MaMucDo");

                    b.HasIndex("MaTrangThai");

                    b.ToTable("CONG_VIEC", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.CtChiPhi", b =>
                {
                    b.Property<int>("MaChiTietCp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaChiTietCP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietCp"));

                    b.Property<string>("LoaiChiPhi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaChiPhi")
                        .HasColumnType("int");

                    b.Property<int>("MaCongViec")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayChi")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungChiPhi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SoTienDaChi")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChiTietCp");

                    b.HasIndex("MaChiPhi");

                    b.HasIndex("MaCongViec");

                    b.ToTable("CT_CHI_PHI", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.CtCongViec", b =>
                {
                    b.Property<int>("MaChiTietCv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaChiTietCV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietCv"));

                    b.Property<int>("MaCongViec")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungChiTietCv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDungChiTietCV");

                    b.HasKey("MaChiTietCv");

                    b.HasIndex("MaCongViec");

                    b.ToTable("CT_CONG_VIEC", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.CtDanhGiaDuAn", b =>
                {
                    b.Property<int>("MaChiTietDgda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaChiTietDGDA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietDgda"));

                    b.Property<int?>("DiemDanhGiaDa")
                        .HasColumnType("int")
                        .HasColumnName("DiemDanhGiaDA");

                    b.Property<int>("MaDanhGiaDuAn")
                        .HasColumnType("int");

                    b.Property<string>("NhanXetDuAn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuChi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChiTietDgda");

                    b.HasIndex("MaDanhGiaDuAn");

                    b.ToTable("CT_DANH_GIA_DU_AN", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.CtDanhGiaNhanVien", b =>
                {
                    b.Property<int>("MaChiTietDgnv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaChiTietDGNV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietDgnv"));

                    b.Property<int?>("DiemDanhGiaNv")
                        .HasColumnType("int")
                        .HasColumnName("DiemDanhGiaNV");

                    b.Property<int>("MaDanhGiaNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("MaKpi")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungDanhGiaNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChiTietDgnv");

                    b.HasIndex("MaDanhGiaNhanVien");

                    b.HasIndex("MaKpi");

                    b.ToTable("CT_DANH_GIA_NHAN_VIEN", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.CtKpiCongViec", b =>
                {
                    b.Property<int>("MaChiTietKpicv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaChiTietKPICV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietKpicv"));

                    b.Property<int?>("DiemKpi")
                        .HasColumnType("int");

                    b.Property<int>("MaKpi")
                        .HasColumnType("int");

                    b.Property<string>("TinhTrangKpi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChiTietKpicv");

                    b.HasIndex("MaKpi");

                    b.ToTable("CT_KPI_CONG_VIEC", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.DanhGiaDuAn", b =>
                {
                    b.Property<int>("MaDanhGiaDuAn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGiaDuAn"));

                    b.Property<int?>("DiemTongDanhGiaDa")
                        .HasColumnType("int")
                        .HasColumnName("DiemTongDanhGiaDA");

                    b.Property<int>("MaDuAn")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDanhGiaDa")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayDanhGiaDA");

                    b.Property<string>("NhanXetTongDuAn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDanhGiaDuAn");

                    b.HasIndex("MaDuAn");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("DANH_GIA_DU_AN", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.DanhGiaNhanVien", b =>
                {
                    b.Property<int>("MaDanhGiaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGiaNhanVien"));

                    b.Property<int?>("DiemTongDanhGiaNv")
                        .HasColumnType("int")
                        .HasColumnName("DiemTongDanhGiaNV");

                    b.Property<int>("MaDuAn")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDanhGia")
                        .HasColumnType("int")
                        .HasColumnName("MaNguoiDanhGia");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDanhGiaNv")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayDanhGiaNV");

                    b.Property<string>("XepLoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDanhGiaNhanVien");

                    b.HasIndex("MaDuAn");

                    b.HasIndex("MaNguoiDanhGia");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("DANH_GIA_NHAN_VIEN", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.DanhMucChucNang", b =>
                {
                    b.Property<int>("MaChucNang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChucNang"));

                    b.Property<int>("MaManHinh")
                        .HasColumnType("int");

                    b.Property<string>("MoTaChucNang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChucNang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChucNang");

                    b.HasIndex("MaManHinh");

                    b.ToTable("DANH_MUC_CHUC_NANG", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.DanhMucCongViec", b =>
                {
                    b.Property<int>("MaDanhMucCv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDanhMucCV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMucCv"));

                    b.Property<int>("MaDuAn")
                        .HasColumnType("int");

                    b.Property<string>("MoTaDanhMucCv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTaDanhMucCV");

                    b.Property<DateTime?>("NgayTaoDmcv")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTaoDMCV");

                    b.Property<string>("TenDanhMucCv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenDanhMucCV");

                    b.HasKey("MaDanhMucCv");

                    b.HasIndex("MaDuAn");

                    b.ToTable("DANH_MUC_CONG_VIEC", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.DanhMucManHinh", b =>
                {
                    b.Property<int>("MaManHinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaManHinh"));

                    b.Property<string>("MoTaManHinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenManHinh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaManHinh");

                    b.ToTable("DANH_MUC_MAN_HINH", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.DuAn", b =>
                {
                    b.Property<int>("MaDuAn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDuAn"));

                    b.Property<int>("MaLoaiDuAn")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("MaTrangThai")
                        .HasColumnType("int");

                    b.Property<string>("MoTaDuAn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDauDuAn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThucDuAn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PhanTramHoanThanh")
                        .HasColumnType("int");

                    b.Property<string>("TenDuAn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDuAn");

                    b.HasIndex("MaLoaiDuAn");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaTrangThai");

                    b.ToTable("DU_AN", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.FileCongViec", b =>
                {
                    b.Property<int>("MaFileCv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaFileCV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaFileCv"));

                    b.Property<string>("DuongDanFileCv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DuongDanFileCV");

                    b.Property<int>("MaCongViec")
                        .HasColumnType("int");

                    b.Property<string>("TenFileCv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenFileCV");

                    b.HasKey("MaFileCv");

                    b.HasIndex("MaCongViec");

                    b.ToTable("FILE_CONG_VIEC", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.FileDuAn", b =>
                {
                    b.Property<int>("MaFileDa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaFileDA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaFileDa"));

                    b.Property<string>("DuongDanFileDa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DuongDanFileDA");

                    b.Property<int>("MaDuAn")
                        .HasColumnType("int");

                    b.Property<string>("TenFileDa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenFileDA");

                    b.HasKey("MaFileDa");

                    b.HasIndex("MaDuAn");

                    b.ToTable("FILE_DU_AN", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.FileTienDoCongViec", b =>
                {
                    b.Property<int>("MaFileTdcv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaFileTDCV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaFileTdcv"));

                    b.Property<string>("DuongDanFileTdcv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DuongDanFileTDCV");

                    b.Property<int>("MaTienDo")
                        .HasColumnType("int");

                    b.Property<string>("TenFileTdcv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenFileTDCV");

                    b.HasKey("MaFileTdcv");

                    b.HasIndex("MaTienDo");

                    b.ToTable("FILE_TIEN_DO_CONG_VIEC", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.KpiCongViec", b =>
                {
                    b.Property<int>("MaKpi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKpi"));

                    b.Property<int?>("DiemTongKpi")
                        .HasColumnType("int");

                    b.Property<string>("LoaiKpi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaCongViec")
                        .HasColumnType("int");

                    b.Property<string>("MoTaKpi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKpi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKpi");

                    b.HasIndex("MaCongViec");

                    b.ToTable("KPI_CONG_VIEC", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.LoaiDuAn", b =>
                {
                    b.Property<int>("MaLoaiDuAn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiDuAn"));

                    b.Property<string>("MoTaLoaiDuAn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoaiDuAn");

                    b.ToTable("LOAI_DU_AN", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.MucDoUuTien", b =>
                {
                    b.Property<int>("MaMucDo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMucDo"));

                    b.Property<string>("MoTaMucDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMucDo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaMucDo");

                    b.ToTable("MUC_DO_UU_TIEN", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("Cccd")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CCCD");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaVaiTro");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[Id] IS NOT NULL");

                    b.ToTable("NHAN_VIEN", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.NhatKyChiPhi", b =>
                {
                    b.Property<int>("MaNhatKyCp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNhatKyCP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhatKyCp"));

                    b.Property<string>("HanhDongNkcp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HanhDongNKCP");

                    b.Property<int>("MaChiPhi")
                        .HasColumnType("int");

                    b.Property<int>("MaCongViec")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<decimal?>("SoTienNkcp")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SoTienNKCP");

                    b.Property<DateTime?>("ThoiGianNkcp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ThoiGianNKCP")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("MaNhatKyCp");

                    b.HasIndex("MaChiPhi");

                    b.HasIndex("MaCongViec");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("NHAT_KY_CHI_PHI", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.NhatKyNhanSu", b =>
                {
                    b.Property<int>("MaNhatKyNs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNhatKyNS");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhatKyNs"));

                    b.Property<string>("HanhDongNkns")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HanhDongNKNS");

                    b.Property<int>("MaCongViec")
                        .HasColumnType("int");

                    b.Property<int>("MaDuAn")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianNkns")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ThoiGianNKNS")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("MaNhatKyNs");

                    b.HasIndex("MaCongViec");

                    b.HasIndex("MaDuAn");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("NHAT_KY_NHAN_SU", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.NhomNhanVien", b =>
                {
                    b.Property<int>("MaNhom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhom"));

                    b.Property<string>("MoTaNhom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhom");

                    b.ToTable("NHOM_NHAN_VIEN", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.PhanCongCongViec", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("MaCongViec")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayGiaoViec")
                        .HasColumnType("datetime2");

                    b.Property<string>("VaiTro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhanVien", "MaCongViec");

                    b.HasIndex("MaCongViec");

                    b.ToTable("PHAN_CONG_CONG_VIEC", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.PhanQuyen", b =>
                {
                    b.Property<int>("MaNhom")
                        .HasColumnType("int");

                    b.Property<int>("MaChucNang")
                        .HasColumnType("int");

                    b.Property<bool?>("CoQuyen")
                        .HasColumnType("bit");

                    b.HasKey("MaNhom", "MaChucNang");

                    b.HasIndex("MaChucNang");

                    b.ToTable("PHAN_QUYEN", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.PhongChat", b =>
                {
                    b.Property<int>("MaPhongChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhongChat"));

                    b.Property<int>("MaDuAn")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhongChat");

                    b.HasIndex("MaDuAn");

                    b.ToTable("PHONG_CHAT", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.ThanhVienDuAn", b =>
                {
                    b.Property<int>("MaDuAn")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayThamGiaDuAn")
                        .HasColumnType("datetime2");

                    b.Property<string>("VaiTroTrongDuAn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDuAn", "MaNhanVien");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("THANH_VIEN_DU_AN", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.ThanhVienNhom", b =>
                {
                    b.Property<int>("MaNhom")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("VaiTroTrongNhom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhom", "MaNhanVien");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("THANH_VIEN_NHOM", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.ThanhVienPhongChat", b =>
                {
                    b.Property<int>("MaPhongChat")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("VaiTroTrongPhongChat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhongChat", "MaNhanVien");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("THANH_VIEN_PHONG_CHAT", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.TienDoCongViec", b =>
                {
                    b.Property<int>("MaTienDo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTienDo"));

                    b.Property<string>("GhiChuTienDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaCongViec")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int?>("PhanTram")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TrangThaiTienDo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTienDo");

                    b.HasIndex("MaCongViec");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("TIEN_DO_CONG_VIEC", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.TinNhan", b =>
                {
                    b.Property<int>("MaTinNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinNhan"));

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("MaPhongChat")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungTinNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("MaTinNhan");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaPhongChat");

                    b.ToTable("TIN_NHAN", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.TrangThai", b =>
                {
                    b.Property<int>("MaTrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTrangThai"));

                    b.Property<string>("LoaiTrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaTrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTrangThai");

                    b.ToTable("TRANG_THAI", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAn.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VAI_TRO", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("QuanLyDuAn.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("QuanLyDuAn.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("QuanLyDuAn.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.AiDataset", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.CongViec", null)
                        .WithMany()
                        .HasForeignKey("MaCongViec")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Models.DuAn", null)
                        .WithMany()
                        .HasForeignKey("MaDuAn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.AiKetQua", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.DuAn", null)
                        .WithMany()
                        .HasForeignKey("MaDuAn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Models.AiModel", null)
                        .WithMany()
                        .HasForeignKey("MaModel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.AiLichSuDuDoan", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.CongViec", null)
                        .WithMany()
                        .HasForeignKey("MaCongViec")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Models.AiModel", null)
                        .WithMany()
                        .HasForeignKey("MaModel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.AiNguyenNhan", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.CongViec", null)
                        .WithMany()
                        .HasForeignKey("MaCongViec")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.ChiPhi", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.DuAn", null)
                        .WithMany()
                        .HasForeignKey("MaDuAn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Models.NhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.CongViec", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.DanhMucCongViec", null)
                        .WithMany()
                        .HasForeignKey("MaDanhMucCv")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Models.MucDoUuTien", null)
                        .WithMany()
                        .HasForeignKey("MaMucDo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Models.TrangThai", null)
                        .WithMany()
                        .HasForeignKey("MaTrangThai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.CtChiPhi", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.ChiPhi", null)
                        .WithMany()
                        .HasForeignKey("MaChiPhi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Models.CongViec", null)
                        .WithMany()
                        .HasForeignKey("MaCongViec")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.CtCongViec", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.CongViec", null)
                        .WithMany()
                        .HasForeignKey("MaCongViec")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.CtDanhGiaDuAn", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.DanhGiaDuAn", null)
                        .WithMany()
                        .HasForeignKey("MaDanhGiaDuAn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.CtDanhGiaNhanVien", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.DanhGiaNhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaDanhGiaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Models.KpiCongViec", null)
                        .WithMany()
                        .HasForeignKey("MaKpi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.CtKpiCongViec", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.KpiCongViec", null)
                        .WithMany()
                        .HasForeignKey("MaKpi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.DanhGiaDuAn", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.DuAn", null)
                        .WithMany()
                        .HasForeignKey("MaDuAn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Models.NhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.DanhGiaNhanVien", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.DuAn", null)
                        .WithMany()
                        .HasForeignKey("MaDuAn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Models.NhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNguoiDanhGia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Models.NhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.DanhMucChucNang", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.DanhMucManHinh", null)
                        .WithMany()
                        .HasForeignKey("MaManHinh")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.DanhMucCongViec", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.DuAn", null)
                        .WithMany()
                        .HasForeignKey("MaDuAn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.DuAn", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.LoaiDuAn", null)
                        .WithMany()
                        .HasForeignKey("MaLoaiDuAn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Models.NhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Models.TrangThai", null)
                        .WithMany()
                        .HasForeignKey("MaTrangThai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.FileCongViec", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.CongViec", null)
                        .WithMany()
                        .HasForeignKey("MaCongViec")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.FileDuAn", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.DuAn", null)
                        .WithMany()
                        .HasForeignKey("MaDuAn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.FileTienDoCongViec", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.TienDoCongViec", null)
                        .WithMany()
                        .HasForeignKey("MaTienDo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.KpiCongViec", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.CongViec", null)
                        .WithMany()
                        .HasForeignKey("MaCongViec")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.NhanVien", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.VaiTro", null)
                        .WithMany()
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Data.ApplicationUser", "User")
                        .WithOne("NhanVien")
                        .HasForeignKey("QuanLyDuAn.Models.NhanVien", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyDuAn.Models.NhatKyChiPhi", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.ChiPhi", null)
                        .WithMany()
                        .HasForeignKey("MaChiPhi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Models.CongViec", null)
                        .WithMany()
                        .HasForeignKey("MaCongViec")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Models.NhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.NhatKyNhanSu", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.CongViec", null)
                        .WithMany()
                        .HasForeignKey("MaCongViec")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Models.DuAn", null)
                        .WithMany()
                        .HasForeignKey("MaDuAn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Models.NhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.PhanCongCongViec", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.CongViec", null)
                        .WithMany()
                        .HasForeignKey("MaCongViec")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Models.NhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.PhanQuyen", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.DanhMucChucNang", null)
                        .WithMany()
                        .HasForeignKey("MaChucNang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Models.NhomNhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNhom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.PhongChat", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.DuAn", null)
                        .WithMany()
                        .HasForeignKey("MaDuAn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.ThanhVienDuAn", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.DuAn", null)
                        .WithMany()
                        .HasForeignKey("MaDuAn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Models.NhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.ThanhVienNhom", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.NhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Models.NhomNhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNhom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.ThanhVienPhongChat", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.NhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Models.PhongChat", null)
                        .WithMany()
                        .HasForeignKey("MaPhongChat")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.TienDoCongViec", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.CongViec", null)
                        .WithMany()
                        .HasForeignKey("MaCongViec")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Models.NhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Models.TinNhan", b =>
                {
                    b.HasOne("QuanLyDuAn.Models.NhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Models.PhongChat", null)
                        .WithMany()
                        .HasForeignKey("MaPhongChat")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDuAn.Data.ApplicationUser", b =>
                {
                    b.Navigation("NhanVien");
                });
#pragma warning restore 612, 618
        }
    }
}
